# Generated by Django 2.2.1 on 2020-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='authoe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='typpe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
    ]
