# Generated by Django 2.2.1 on 2020-02-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='作者名字')),
                ('gender', models.CharField(max_length=32, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'author',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='类型名字')),
                ('description', models.TextField(verbose_name='描述')),
            ],
            options={
                'db_table': 'type',
                'verbose_name_plural': '文章类型',
            },
        ),
        migrations.DeleteModel(
            name='authoe',
        ),
        migrations.DeleteModel(
            name='typpe',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章表'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(verbose_name='时间日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='文章描述'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=32, verbose_name='标题'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AddField(
            model_name='type',
            name='article',
            field=models.ManyToManyField(to='article.Article'),
        ),
    ]
