"""
Django settings for Demo project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# __file__ 当前文件的路劲
# abspath 决定路径
# dirname 文件的目录
# BASE_DIR django提供的项目点根目录
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
print(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 秘钥
SECRET_KEY = '21t$2e!(soejo*=-oe@0yq*&p!n)+l@x)-=-x^%%)r1g!2a89#'

# SECURITY WARNING: don't run with debug turned on in production!
# debug 模式
# 作用  1当代码改变是自动重启项目  2 在客户端和控制台显示报错内容
DEBUG = True
# 白名单
ALLOWED_HOSTS = []


# Application definition
#注册子应用
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01',
    'app01.templatetags',
    'ckeditor',
    'ckeditor_uploader',
]
# 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#跟路由地址
ROOT_URLCONF = 'Demo.urls'
# 模板配置
TEMPLATES = [
    {
        ##使用的魔板引擎
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  #django的模板引擎
        # 'BACKEND': 'django.template.backends.jinja2'  #jinja2的引擎
        #模板文件的目录配置 列表
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        #APP_DIRS 设置是否在子应用中自动寻找模板内容
        #true是自动寻找
        'APP_DIRS': True,
        #是一些针对后端的设置
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
#内置服务器
WSGI_APPLICATION = 'Demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# 数据库配置
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES={
    'default':{
        'ENGINE':'django.db.backends.mysql',
        'HOST':'127.0.0.1',
        'USER':'root',
        'PASSWORD':'123456',
        'PORT':'3306',
        'NAME':'app'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
# 权限
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
# 语言
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/shanghai'

USE_I18N = True

USE_L10N = True
# 是否使用默认时区  true是内置时区
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
#静态文件的路由
STATIC_URL = '/static/'
#静态文件的目录地址
STATICFILES_DIRS=(
    os.path.join(BASE_DIR,"static"),
)

MEDIA_URL='/media/'
##文件上传路径
MEDIA_ROOT=os.path.join(BASE_DIR,'static')


##基于ckeditor的上传地址
CKEDITOR_UPLOAD_PATH='static/upload'
##图片使用的模版
CKEDITOR_IMAGE_BACKEND='pillow'


