# Generated by Django 2.2.1 on 2020-02-17 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='作者名字')),
                ('gender', models.CharField(choices=[(0, '女'), (1, '男')], max_length=32, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'author',
                'verbose_name_plural': '作者',
                'verbose_name': '作者',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='类型名字')),
                ('description', models.TextField(verbose_name='描述')),
            ],
            options={
                'db_table': 'type',
                'verbose_name_plural': '文章类型',
                'verbose_name': '文章类型',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('date', models.DateField(verbose_name='时间日期')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('description', models.TextField(verbose_name='文章描述')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Author')),
                ('type', models.ManyToManyField(to='app01.Type')),
            ],
            options={
                'db_table': 'article',
                'verbose_name_plural': '文章表',
                'verbose_name': '文章表',
            },
        ),
    ]
