# Generated by Django 2.2.1 on 2020-02-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200217_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='cxk.gif', upload_to='images', verbose_name='图片'),
            preserve_default=False,
        ),
    ]
