# Generated by Django 2.2.1 on 2020-02-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='学科的名字')),
                ('start_time', models.DateField(verbose_name='开始时间')),
            ],
            options={
                'db_table': 'subject',
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
