# Generated by Django 2.2.1 on 2020-02-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(verbose_name='用户的年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='111@qq.com', max_length=254, verbose_name='用户的邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='用户的手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=32, verbose_name='用户的名'),
        ),
    ]
