# Generated by Django 2.2.1 on 2020-02-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_book_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '书'},
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={'verbose_name_plural': '出版社'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
