# Generated by Django 2.2.1 on 2020-02-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20200213_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='学生姓名')),
                ('age', models.IntegerField(verbose_name='学生年龄')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='老师姓名')),
                ('gender', models.IntegerField(verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('preson', models.ManyToManyField(to='app01.Preson')),
            ],
        ),
    ]
