# Generated by Django 2.2.1 on 2020-02-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_preson_teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='preson',
            table='preson',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
